/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SubscriptionRouteImport } from './routes/subscription/route'
import { Route as SettingsRouteImport } from './routes/settings/route'
import { Route as IndexImport } from './routes/index'
import { Route as SubscriptionIndexImport } from './routes/subscription/index'
import { Route as SettingsIndexImport } from './routes/settings/index'
import { Route as ChatIndexImport } from './routes/chat/index'
import { Route as SubscriptionUsageImport } from './routes/subscription/usage'
import { Route as SubscriptionPlanImport } from './routes/subscription/plan'
import { Route as SubscriptionBillingImport } from './routes/subscription/billing'
import { Route as SettingsCommonImport } from './routes/settings/common'
import { Route as SettingsProviderRouteImport } from './routes/settings/provider/route'
import { Route as SettingsProviderIndexImport } from './routes/settings/provider/index'
import { Route as SettingsProviderProviderIdImport } from './routes/settings/provider/$providerId'

// Create/Update Routes

const SubscriptionRouteRoute = SubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => rootRoute,
} as any)

const SettingsRouteRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SubscriptionIndexRoute = SubscriptionIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubscriptionRouteRoute,
} as any)

const SettingsIndexRoute = SettingsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const ChatIndexRoute = ChatIndexImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRoute,
} as any)

const SubscriptionUsageRoute = SubscriptionUsageImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => SubscriptionRouteRoute,
} as any)

const SubscriptionPlanRoute = SubscriptionPlanImport.update({
  id: '/plan',
  path: '/plan',
  getParentRoute: () => SubscriptionRouteRoute,
} as any)

const SubscriptionBillingRoute = SubscriptionBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => SubscriptionRouteRoute,
} as any)

const SettingsCommonRoute = SettingsCommonImport.update({
  id: '/common',
  path: '/common',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsProviderRouteRoute = SettingsProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => SettingsRouteRoute,
} as any)

const SettingsProviderIndexRoute = SettingsProviderIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsProviderRouteRoute,
} as any)

const SettingsProviderProviderIdRoute = SettingsProviderProviderIdImport.update(
  {
    id: '/$providerId',
    path: '/$providerId',
    getParentRoute: () => SettingsProviderRouteRoute,
  } as any,
)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRoute
    }
    '/subscription': {
      id: '/subscription'
      path: '/subscription'
      fullPath: '/subscription'
      preLoaderRoute: typeof SubscriptionRouteImport
      parentRoute: typeof rootRoute
    }
    '/settings/provider': {
      id: '/settings/provider'
      path: '/provider'
      fullPath: '/settings/provider'
      preLoaderRoute: typeof SettingsProviderRouteImport
      parentRoute: typeof SettingsRouteImport
    }
    '/settings/common': {
      id: '/settings/common'
      path: '/common'
      fullPath: '/settings/common'
      preLoaderRoute: typeof SettingsCommonImport
      parentRoute: typeof SettingsRouteImport
    }
    '/subscription/billing': {
      id: '/subscription/billing'
      path: '/billing'
      fullPath: '/subscription/billing'
      preLoaderRoute: typeof SubscriptionBillingImport
      parentRoute: typeof SubscriptionRouteImport
    }
    '/subscription/plan': {
      id: '/subscription/plan'
      path: '/plan'
      fullPath: '/subscription/plan'
      preLoaderRoute: typeof SubscriptionPlanImport
      parentRoute: typeof SubscriptionRouteImport
    }
    '/subscription/usage': {
      id: '/subscription/usage'
      path: '/usage'
      fullPath: '/subscription/usage'
      preLoaderRoute: typeof SubscriptionUsageImport
      parentRoute: typeof SubscriptionRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatIndexImport
      parentRoute: typeof rootRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexImport
      parentRoute: typeof SettingsRouteImport
    }
    '/subscription/': {
      id: '/subscription/'
      path: '/'
      fullPath: '/subscription/'
      preLoaderRoute: typeof SubscriptionIndexImport
      parentRoute: typeof SubscriptionRouteImport
    }
    '/settings/provider/$providerId': {
      id: '/settings/provider/$providerId'
      path: '/$providerId'
      fullPath: '/settings/provider/$providerId'
      preLoaderRoute: typeof SettingsProviderProviderIdImport
      parentRoute: typeof SettingsProviderRouteImport
    }
    '/settings/provider/': {
      id: '/settings/provider/'
      path: '/'
      fullPath: '/settings/provider/'
      preLoaderRoute: typeof SettingsProviderIndexImport
      parentRoute: typeof SettingsProviderRouteImport
    }
  }
}

// Create and export the route tree

interface SettingsProviderRouteRouteChildren {
  SettingsProviderProviderIdRoute: typeof SettingsProviderProviderIdRoute
  SettingsProviderIndexRoute: typeof SettingsProviderIndexRoute
}

const SettingsProviderRouteRouteChildren: SettingsProviderRouteRouteChildren = {
  SettingsProviderProviderIdRoute: SettingsProviderProviderIdRoute,
  SettingsProviderIndexRoute: SettingsProviderIndexRoute,
}

const SettingsProviderRouteRouteWithChildren =
  SettingsProviderRouteRoute._addFileChildren(
    SettingsProviderRouteRouteChildren,
  )

interface SettingsRouteRouteChildren {
  SettingsProviderRouteRoute: typeof SettingsProviderRouteRouteWithChildren
  SettingsCommonRoute: typeof SettingsCommonRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsProviderRouteRoute: SettingsProviderRouteRouteWithChildren,
  SettingsCommonRoute: SettingsCommonRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

interface SubscriptionRouteRouteChildren {
  SubscriptionBillingRoute: typeof SubscriptionBillingRoute
  SubscriptionPlanRoute: typeof SubscriptionPlanRoute
  SubscriptionUsageRoute: typeof SubscriptionUsageRoute
  SubscriptionIndexRoute: typeof SubscriptionIndexRoute
}

const SubscriptionRouteRouteChildren: SubscriptionRouteRouteChildren = {
  SubscriptionBillingRoute: SubscriptionBillingRoute,
  SubscriptionPlanRoute: SubscriptionPlanRoute,
  SubscriptionUsageRoute: SubscriptionUsageRoute,
  SubscriptionIndexRoute: SubscriptionIndexRoute,
}

const SubscriptionRouteRouteWithChildren =
  SubscriptionRouteRoute._addFileChildren(SubscriptionRouteRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/subscription': typeof SubscriptionRouteRouteWithChildren
  '/settings/provider': typeof SettingsProviderRouteRouteWithChildren
  '/settings/common': typeof SettingsCommonRoute
  '/subscription/billing': typeof SubscriptionBillingRoute
  '/subscription/plan': typeof SubscriptionPlanRoute
  '/subscription/usage': typeof SubscriptionUsageRoute
  '/chat': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider/': typeof SettingsProviderIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings/common': typeof SettingsCommonRoute
  '/subscription/billing': typeof SubscriptionBillingRoute
  '/subscription/plan': typeof SubscriptionPlanRoute
  '/subscription/usage': typeof SubscriptionUsageRoute
  '/chat': typeof ChatIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/subscription': typeof SubscriptionIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider': typeof SettingsProviderIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/settings': typeof SettingsRouteRouteWithChildren
  '/subscription': typeof SubscriptionRouteRouteWithChildren
  '/settings/provider': typeof SettingsProviderRouteRouteWithChildren
  '/settings/common': typeof SettingsCommonRoute
  '/subscription/billing': typeof SubscriptionBillingRoute
  '/subscription/plan': typeof SubscriptionPlanRoute
  '/subscription/usage': typeof SubscriptionUsageRoute
  '/chat/': typeof ChatIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/subscription/': typeof SubscriptionIndexRoute
  '/settings/provider/$providerId': typeof SettingsProviderProviderIdRoute
  '/settings/provider/': typeof SettingsProviderIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/subscription'
    | '/settings/provider'
    | '/settings/common'
    | '/subscription/billing'
    | '/subscription/plan'
    | '/subscription/usage'
    | '/chat'
    | '/settings/'
    | '/subscription/'
    | '/settings/provider/$providerId'
    | '/settings/provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings/common'
    | '/subscription/billing'
    | '/subscription/plan'
    | '/subscription/usage'
    | '/chat'
    | '/settings'
    | '/subscription'
    | '/settings/provider/$providerId'
    | '/settings/provider'
  id:
    | '__root__'
    | '/'
    | '/settings'
    | '/subscription'
    | '/settings/provider'
    | '/settings/common'
    | '/subscription/billing'
    | '/subscription/plan'
    | '/subscription/usage'
    | '/chat/'
    | '/settings/'
    | '/subscription/'
    | '/settings/provider/$providerId'
    | '/settings/provider/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  SubscriptionRouteRoute: typeof SubscriptionRouteRouteWithChildren
  ChatIndexRoute: typeof ChatIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  SubscriptionRouteRoute: SubscriptionRouteRouteWithChildren,
  ChatIndexRoute: ChatIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/settings",
        "/subscription",
        "/chat/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/settings": {
      "filePath": "settings/route.tsx",
      "children": [
        "/settings/provider",
        "/settings/common",
        "/settings/"
      ]
    },
    "/subscription": {
      "filePath": "subscription/route.tsx",
      "children": [
        "/subscription/billing",
        "/subscription/plan",
        "/subscription/usage",
        "/subscription/"
      ]
    },
    "/settings/provider": {
      "filePath": "settings/provider/route.tsx",
      "parent": "/settings",
      "children": [
        "/settings/provider/$providerId",
        "/settings/provider/"
      ]
    },
    "/settings/common": {
      "filePath": "settings/common.tsx",
      "parent": "/settings"
    },
    "/subscription/billing": {
      "filePath": "subscription/billing.tsx",
      "parent": "/subscription"
    },
    "/subscription/plan": {
      "filePath": "subscription/plan.tsx",
      "parent": "/subscription"
    },
    "/subscription/usage": {
      "filePath": "subscription/usage.tsx",
      "parent": "/subscription"
    },
    "/chat/": {
      "filePath": "chat/index.tsx"
    },
    "/settings/": {
      "filePath": "settings/index.tsx",
      "parent": "/settings"
    },
    "/subscription/": {
      "filePath": "subscription/index.tsx",
      "parent": "/subscription"
    },
    "/settings/provider/$providerId": {
      "filePath": "settings/provider/$providerId.tsx",
      "parent": "/settings/provider"
    },
    "/settings/provider/": {
      "filePath": "settings/provider/index.tsx",
      "parent": "/settings/provider"
    }
  }
}
ROUTE_MANIFEST_END */
