name: Test
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install Dependencies
        run: |
          pnpm install

      - name: Check Code Formatting
        run: |
          # Run format command to format code
          pnpm run fmt
          # Check if there are any changes after formatting
          if ! git diff --quiet --exit-code; then
            echo "❌ Code is not properly formatted! Please run 'pnpm run fmt' locally and commit the changes."
            echo "Files with formatting issues:"
            git diff --name-only
            echo "Diff details:"
            git diff
            exit 1
          else
            echo "✅ Code formatting is correct!"
          fi

      - name: Build
        run: |
          pnpm run build
